"""enforce one running run per thread

Revision ID: 7f662d465cc8
Revises: 9545014af75a
Create Date: 2026-08-02 11:52:28.589724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f662d465cc8"
down_revision: str | Sequence[str] | None = "9545014af75a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_runs_one_running_per_thread",
        "runs",
        ["thread_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_runs_one_running_per_thread",
        table_name="runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    # ### end Alembic commands ###
