"""record run token usage

Revision ID: b635e4484f87
Revises: 7f662d465cc8
Create Date: 2026-08-02 12:26:17.180613

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b635e4484f87"
down_revision: str | Sequence[str] | None = "7f662d465cc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("runs", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.add_column("runs", sa.Column("model_request_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "model_request_count")
    op.drop_column("runs", "output_tokens")
    op.drop_column("runs", "input_tokens")
    # ### end Alembic commands ###
